### ISSUE TITLE
Не компилируются тесты

### ISSUE THREAD

**Issue by gennady-lebedev** [rkovalev/auction#1]
В build.gradle есть зависимость `testCompile group: 'junit', name: 'junit', version: '4.12'` при том что в тесте com.tehb.AuctionDiscreteTest используются конструкции из junit.jupiter.

Сейчас проект не компилируется, если не поправить зависимость на `testCompile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.3.1'`

**Comment by rkovalev** [comment]
fixed
